[project]
name = "ai-youtuber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohappyeyeballs>=2.4.4",
    "aiohttp>=3.11.11",
    "browser-use>=0.1.19",
    "google-auth-oauthlib>=1.2.1",
    "langchain-chroma>=0.2.0",
    "langchain-google-genai>=2.0.8",
    "langchain-huggingface>=0.1.2",
    "langchain-openai>=0.3.0",
    "langgraph>=0.2.62",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "pywin32>=308",
    "sentencepiece>=0.2.0",
    "websockets>=14.1",
]
